export const GET_BLOG_REQUEST = "GET_BLOG_REQUEST";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_FAILURE = "GET_BLOG_FAILURE";



export const GET_USER_BLOGS_REQUEST = "GET_USER_BLOGS_REQUEST";
export const GET_USER_BLOGS_SUCCESS = "GET_USER_BLOGS_SUCCESS";
export const GET_USER_BLOGS_FAILURE = "GET_USER_BLOGS_FAILURE";


export const DELETE_USER_BLOGS_REQUREST = "DELETE_USER_BLOGS_REQUREST";
export const DELETE_USER_BLOGS_SUCCESS = "DELETE_USER_BLOGS_SUCCESS";
export const DELETE_USER_BLOGS_FAILURE = "DELETE_USER_BLOGS_FAILURE";




export const CREATE_USER_BLOGS_REQUREST = "CREATE_USER_BLOGS_REQUREST";
export const CREATE_USER_BLOGS_SUCCESS = "CREATE_USER_BLOGS_SUCCESS";
export const CREATE_USER_BLOGS_FAILURE = "CREATE_USER_BLOGS_FAILURE";